# Generated by Django 6.0.6 on 2026-06-26 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee Report'), ('PROJECT', 'Project Report'), ('TASK', 'Task Report'), ('PERFORMANCE', 'Performance Analytics')], max_length=20)),
                ('format', models.CharField(choices=[('EXCEL', 'Excel Spreadsheet'), ('PDF', 'Portable Document Format')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
