# Generated by Django 6.0.6 on 2026-06-26 09:56

import django.db.models.deletion
import notifications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(validators=[notifications.validators.validate_notification_content])),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('EMAIL', 'Email Alert')], default='IN_APP', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
