# Generated by Django 6.0.6 on 2026-06-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_parent_message_message_starred_by_auditlog_and_more'),
        ('notifications', '0002_notification_category_notification_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='messaging.conversation'),
        ),
    ]
