# Generated by Django 6.0.6 on 2026-06-27 10:50

import core.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/', validators=[core.file_validators.validate_safe_upload]),
        ),
    ]
