# Generated by Django 6.0.6 on 2026-06-26 09:56

import design_module.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_screens_count', models.IntegerField(default=1, validators=[design_module.validators.validate_positive_count])),
                ('status', models.CharField(choices=[('WIREFRAME', 'Wireframe'), ('MOCKUP', 'Mockup'), ('PROTOTYPE', 'Prototype'), ('COMPLETED', 'Completed')], default='WIREFRAME', max_length=20)),
                ('client_feedback', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('revision_count', models.IntegerField(default=0)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_task', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='DesignRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('feedback', models.TextField()),
                ('changes_made', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('design_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='design_module.designtask')),
            ],
        ),
    ]
