# Generated by Django 6.0.6 on 2026-06-26 09:56

import dev_module.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(choices=[('API', 'API Development'), ('MOBILE', 'Mobile Development'), ('WEB', 'Web Development')], default='WEB', max_length=15)),
                ('test_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('bug_count', models.IntegerField(default=0)),
                ('deployment_status', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='LOCAL', max_length=15)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_task', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(validators=[dev_module.validators.validate_bug_description])),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('CLOSED', 'Closed')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('dev_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='dev_module.devtask')),
            ],
        ),
    ]
