# Generated by Django 6.0.6 on 2026-06-27 10:50

import core.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_attachment_edit_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/', validators=[core.file_validators.validate_safe_upload]),
        ),
    ]
