# Generated by Django 6.0.6 on 2026-06-26 09:56

import django.db.models.deletion
import django.utils.timezone
import worklogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[worklogs.validators.validate_work_hours])),
                ('notes', models.TextField()),
                ('blockers', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='employees.employeeprofile')),
            ],
        ),
    ]
