# Generated by Django 6.0.7 on 2026-07-16 09:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_address_company_email_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='modules_config',
            field=models.JSONField(blank=True, default=core.models.default_modules_config),
        ),
    ]
